# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f27684f83ce94fa2c9b9979b92bdc3db4becba95e2bfb9236fc6ae89b5023098cf43be9bc1dac84d4fa91620d9eb4bbb0dcaab425bd8fc2c419ef556d39d9bce

test:
  secret_key_base: bbd81bccb383b230fffe4885126ca39a0d47b1aaf6229dbeeabcd09c76ded52d1d8dda41d04eb83ed7ccb2ce626538465ffd0521275eb8b9ee79ba946c3f9352

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
